### ISSUE TITLE
Automated script

### ISSUE THREAD

**Issue by Lyceris-chan** [moadfakhri/SpotifyAdBlocker-Windows#2]
Hey first of all thanks for your work ^^,

I wrote a batch script which automatically downloads the latest release and changes the files required after which it cleans up after itself.

The script can be found [here](https://github.com/Lyceris-chan/Spotify-adblock) and you are more then welcome to include it into your repo if you want.

**Comment by moadfakhri** [comment]
Oh thank you very much for the script!
I will add a reference to your repository in the readme as an alternative way to set up the adblocker.

**Comment by moadfakhri** [comment]
Done!
Thank you again.
